-- Migration 001: Initial Schema
-- APG Website: Firebase → Supabase migration
-- Creates all tables, enums, constraints, and foreign keys
-- Applied via: Supabase MCP `apply_migration`

-- ============ ENUMS ============
CREATE TYPE user_role AS ENUM ('owner', 'moderator', 'admin');
-- ============ PROFILES (replaces Firestore `users/{uid}`) ============
-- Linked 1:1 with auth.users; auto-created by trigger on auth.users INSERT
CREATE TABLE public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username text,
    display_name text,
    role user_role NOT NULL DEFAULT 'moderator',
    email text,
    profile_image text,
    created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
-- ============ OFFERINGS (replaces Firestore `offerings`) ============
CREATE TABLE public.offerings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    location text,
    property_type text,
    sub_property_type text,
    status text NOT NULL DEFAULT 'available',
    price numeric,
    min_price numeric,
    max_price numeric,
    price_unit text DEFAULT 'PHP',
    floor_area numeric,
    lot_area numeric,
    description text,
    email text,
    phone text,
    images jsonb DEFAULT '[]'::jsonb,
    admin_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.offerings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offerings ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
        to_tsvector('english', coalesce(title, '') || ' ' || coalesce(location, '') || ' ' || coalesce(property_type, '') || ' ' || coalesce(description, ''))
    ) STORED;
CREATE INDEX idx_offerings_search ON public.offerings USING GIN(search_vector);
-- ============ OFFERING COMMENTS ============
CREATE TABLE public.offering_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offering_id bigint NOT NULL REFERENCES public.offerings(id) ON DELETE CASCADE,
    user_name text NOT NULL,
    comment_text text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.offering_comments ENABLE ROW LEVEL SECURITY;
-- ============ OFFERING RATINGS ============
CREATE TABLE public.offering_ratings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offering_id bigint NOT NULL REFERENCES public.offerings(id) ON DELETE CASCADE,
    user_ip text,
    rating smallint NOT NULL CHECK (rating >= 1 AND rating <= 5),
    created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.offering_ratings ENABLE ROW LEVEL SECURITY;
-- ============ OFFERING REACTIONS / LIKES ============
CREATE TABLE public.offering_reactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offering_id bigint NOT NULL REFERENCES public.offerings(id) ON DELETE CASCADE,
    user_ip text,
    reaction_type text NOT NULL DEFAULT 'like',
    created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.offering_reactions ENABLE ROW LEVEL SECURITY;
-- ============ SERVICES ============
CREATE TABLE public.services (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    text_color text,
    website_link text,
    card_image text,
    card_logo text,
    created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
-- ============ CAREERS ============
CREATE TABLE public.careers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    type text,
    location text,
    work_setup text,
    key_responsibilities text,
    description text,
    admin_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.careers ENABLE ROW LEVEL SECURITY;
-- ============ BLOGS ============
CREATE TABLE public.blogs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    author text,
    content text,
    date_published timestamptz,
    image text,
    author_image text,
    category text,
    excerpt text
);
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
-- ============ INQUIRIES ============
CREATE TABLE public.inquiries (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    email text,
    subject text,
    message text,
    contact text,
    business text,
    location text,
    note text,
    status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'read', 'replied', 'archived')),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT inquiries_name_length CHECK (length(name) > 0 AND length(name) <= 200),
    CONSTRAINT inquiries_email_format CHECK (email IS NULL OR email ~ '^[^@]+@[^@]+\.[^@]+$'),
    CONSTRAINT inquiries_message_length CHECK (message IS NULL OR (length(message) > 0 AND length(message) <= 5000))
);
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
-- ============ CHAT SESSIONS ============
CREATE TABLE public.chat_sessions (
    id text PRIMARY KEY,
    session_id text,
    visitor_name text,
    visitor_email text,
    visitor_session_token text,
    last_active timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    visitor_peer_id text,
    admin_peer_id text,
    call_status text DEFAULT 'none'
);
ALTER TABLE public.chat_sessions ENABLE ROW LEVEL SECURITY;
-- ============ CHAT MESSAGES ============
CREATE TABLE public.chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
    visitor_name text,
    visitor_email text,
    message text,
    sender_type text CHECK (sender_type IN ('visitor', 'admin', 'user', 'bot')),
    is_read boolean DEFAULT false,
    image_url text,
    created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
